### ISSUE TITLE
Update to dependencies (add composer)

### ISSUE THREAD

**Issue by jimblue** [dimitrilongo/grav-plugin-mobile-detect#3]
Hi!

First thank you for this nice plugin.

I was wondering why don't you use Composer to handle dependencies.

Also could you update Mobile-Detect to the latest: `2.8.30 ``

Cheers!

**Comment by dimitrilongo** [comment]
hi!

i'v just update to the latest class (2.8.30)

just wait to see it in the `gpm` or download [here](https://github.com/dimitrilongo/grav-plugin-mobile-detect/releases/tag/v1.3.2)

Concerning `composer`, i will consider to add `composer`in a future release.

thanks

**Comment by jimblue** [comment]
Hey! Thank for you fast answer.

About `composer` you should do it, it's a 5min implementation but much more time gain over time 😄 !

**Comment by dimitrilongo** [comment]
@jimblue better late than never, composer.json is here  ;-)

**Comment by jimblue** [comment]
Good job !
