### ISSUE TITLE
[ Feature request ] Detect touch device

### ISSUE THREAD

**Issue by jimblue** [dimitrilongo/grav-plugin-mobile-detect#5]
Hi @dimitrilongo !

Thanks for this nice plugin.

Do you think it's possible to detect if user device have touch support?

**Comment by dimitrilongo** [comment]
hi

sorry for delay. But Mobile_Detect class detect only with HTTP headers and User Agent.

I think you're looking for something like https://github.com/rafrex/detect-it

**Comment by jimblue** [comment]
Hi @dimitrilongo,

No worries and thanks for the link!
