### ISSUE TITLE
v 1.4 doesn't work after updating

### ISSUE THREAD

**Issue by valkanx** [dimitrilongo/grav-plugin-mobile-detect#9]
Hi,
I use the very last version of grav and tried to upgrade mobile-detect to versions 1.4.x but it didn't work. I got a "failed to open stream: No such file or directory" on /mobiledetect/mobiledetectlib/Mobile_Detect.php.
I went back to 1.3.x and things worked again.

**Comment by dimitrilongo** [comment]
hi,

thank for the feed back i check today

**Comment by dimitrilongo** [comment]
publish [new release](https://github.com/dimitrilongo/grav-plugin-mobile-detect/releases/tag/v1.4.2) Fixed
